### ISSUE TITLE
[mac] impossible de charger une image

### ISSUE THREAD

**Issue by Menencia** [thegeektree/espers#2]
Il y a encore une image qui ne veut pas se charger dans l'histoire de Nheal, quand il dit "je dois remettre mes lunettes..."

![capture d ecran 2016-08-22 a 20 34 46](https://cloud.githubusercontent.com/assets/442097/17866792/30363606-68a8-11e6-9641-c55060e8f942.png)

**Comment by thegeektree** [comment]
réglé, nouvelle version sur le drive :)
