### ISSUE TITLE
[PC] Problème scène ascenseur (Attention spoil !)

### ISSUE THREAD

**Issue by Yoshisoro** [thegeektree/espers#4]
- Quand tu as le choix de sortir ou rester et que tu choisis de sortir, tu peux re rentrer dans l'ascenseur et les dialogues recommence à partir du choix choix de se présenter ou non.
- Quand on choisit de sortir et qu'on clique sur l’ascenseur à droite, on a le texte "Mme smith m'attend dans l'autre ascenseur" ce qui est faux puisqu'on vient d'en descendre 
- Petite faute d'orthographe lors du dialogue sur le laboratoire (j'avais dit attention spoil ! :p) 
  ![capture](https://cloud.githubusercontent.com/assets/21181234/17870451/e5f5edc4-68b7-11e6-8fc2-08b6aeb04330.PNG)

**Comment by thegeektree** [comment]
Todo Eva : 
- Mettre des interrupteurs de checks sur les évènements automatiques (cad : ascenseur, etc...)
- Supprimer l'event copié par erreur dans le deuxième hall d'accueil -_-' (crétine)
- Corriger la faute d'orthographe.

**Comment by thegeektree** [comment]
All done !
